jQuery(document).ready(function(){jQuery('#languageChooser').popover({container:'body',placement:'bottom',template:'<div class="popover language-popover" role="tooltip"><div class="arrow"></div><div class="popover-content"></div></div>',html:true,content:function(){return jQuery("#languageChooserContent").html();},});jQuery('#loginOrRegister').popover({container:'body',placement:'bottom',template:'<div class="popover login-popover" role="tooltip"><div class="arrow"></div><div class="popover-content"></div></div>',html:true,content:function(){return jQuery("#loginOrRegisterContent").html();},});jQuery("#accountNotifications").popover({container:'body',placement:'bottom',template:'<div class="popover popover-user-notifications" role="tooltip"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>',html:true,content:function(){return jQuery("#accountNotificationsContent").html();},});jQuery('[data-toggle="popover"]').popover({html:true});jQuery('body').on('click',function(e){jQuery('[data-toggle="popover"]').each(function(){if(!jQuery(this).is(e.target)&&jQuery(this).has(e.target).length===0&&jQuery('.popover').has(e.target).length===0){jQuery(this).popover('hide');}});});jQuery(".list-group-tab-nav a").click(function(){if(jQuery(this).hasClass('disabled')){return false;}
jQuery(".list-group-tab-nav a").removeClass('active');jQuery(this).addClass('active');var urlFragment=this.href.split('#')[1];if(urlFragment){window.location.hash='#'+urlFragment;}});if(jQuery(location).attr('hash').substr(1)!=""){var activeTab=jQuery(location).attr('hash');jQuery(".tab-pane").removeClass('active');jQuery(activeTab).removeClass('fade').addClass('active');jQuery(".list-group-tab-nav a").removeClass('active');jQuery('a[href="'+activeTab+'"]').addClass('active');setTimeout(function(){window.scrollTo(0,0);},1);}
if(jQuery.prototype.bootstrapSwitch){jQuery(".toggle-switch-success").bootstrapSwitch({onColor:'success'});}
jQuery(".panel-collapsable .panel-heading").click(function(e){var $this=jQuery(this);if(!$this.parents('.panel').hasClass('panel-collapsed')){$this.parents('.panel').addClass('panel-collapsed').find('.panel-body').slideUp();$this.find('.collapse-icon i').removeClass('fa-minus').addClass('fa-plus');}else{$this.parents('.panel').removeClass('panel-collapsed').find('.panel-body').slideDown();$this.find('.collapse-icon i').removeClass('fa-plus').addClass('fa-minus');}});if(("#frmLogin").length>0){jQuery("#frmLogin input:text:visible:first").focus();}
if(("#twofaactivation").length>0){jQuery("#twofaactivation input:text:visible:first,#twofaactivation input:password:visible:first").focus();}
jQuery("#inputSubaccountActivate").click(function(){if(jQuery("#inputSubaccountActivate:checked").val()!=null){jQuery("#subacct-container").removeClass('hidden');}else{jQuery("#subacct-container").addClass('hidden');}});jQuery(".setBulkAction").click(function(event){event.preventDefault();var id=jQuery(this).attr('id').replace("Link","");if(jQuery("#"+id).length!=0){var action=jQuery("#domainForm").attr("action");jQuery("#domainForm").attr("action",action+"#"+id);}
jQuery("#bulkaction").val(id);jQuery("#domainForm").submit();});jQuery('.stopEventBubble').click(function(event){event.stopPropagation();});jQuery('.tabControlLink').on('click',function(event){event.preventDefault();var id=jQuery(this).attr('href');jQuery("a[href='/"+id+"']").click();});jQuery('.ticket-reply .rating span.star').click(function(event){window.location='viewticket.php?tid='+jQuery(this).parent('.rating').attr("ticketid")+'&c='+jQuery(this).parent('.rating').attr("ticketkey")+'&rating=rate'+jQuery(this).parent('.rating').attr("ticketreplyid")+'_'+jQuery(this).attr("rate");});jQuery('a.autoLinked').click(function(e){e.preventDefault();var child=window.open();child.opener=null;child.location=e.target.href;});jQuery("#inputAllowSso").on('switchChange.bootstrapSwitch',function(event,isChecked){if(isChecked){jQuery("#ssoStatusTextEnabled").removeClass('hidden').show();jQuery("#ssoStatusTextDisabled").hide();}else{jQuery("#ssoStatusTextDisabled").removeClass('hidden').show();jQuery("#ssoStatusTextEnabled").hide();}
jQuery.post("clientarea.php",jQuery("#frmSingleSignOn").serialize());});var count=0,editorName='clientMDE',counter=0;jQuery(".markdown-editor").each(function(index){count++;var autoSaveName=jQuery(this).data('auto-save-name'),footerId=jQuery(this).attr('id')+'-footer';if(typeof autoSaveName=="undefined"){autoSaveName='client_area';}
window[editorName+count.toString()]=jQuery(this).markdown({footer:'<div id="'+footerId+'" class="markdown-editor-status"></div>',autofocus:false,savable:false,resize:'vertical',iconlibrary:'fa',language:locale,onShow:function(e){var content='',save_enabled=false;if(typeof(Storage)!=="undefined"){content=localStorage.getItem(autoSaveName);save_enabled=true;if(content&&typeof(content)!=="undefined"){e.setContent(content);}}
jQuery("#"+footerId).html(parseMdeFooter(content,save_enabled,saved));},onChange:function(e){var content=e.getContent(),save_enabled=false;if(typeof(Storage)!=="undefined"){counter=3;save_enabled=true;localStorage.setItem(autoSaveName,content);doCountdown();}
jQuery("#"+footerId).html(parseMdeFooter(content,save_enabled));},onPreview:function(e){var originalContent=e.getContent(),parsedContent;jQuery.ajax({url:'clientarea.php',async:false,data:{token:csrfToken,action:'parseMarkdown',content:originalContent},success:function(data){parsedContent=JSON.parse(data);}});return parsedContent.body?parsedContent.body:'';},additionalButtons:[[{name:"groupCustom",data:[{name:"cmdHelp",title:"Help",hotkey:"Ctrl+F1",btnClass:"btn open-modal",href:"submitticket.php?action=markdown",icon:{glyph:'glyphicons glyphicons-question-sign',fa:'fa fa-question-circle','fa-3':'icon-question-sign'},callback:function(e){e.$editor.removeClass("md-fullscreen-mode");},additionalAttr:[{name:'data-modal-title',value:markdownGuide}]}]}]]});jQuery(this).closest("form").bind({submit:function(){if(typeof(Storage)!=="undefined"){localStorage.removeItem(autoSaveName);}}});});jQuery('#btnResendVerificationEmail').click(function(){jQuery.post('clientarea.php',{'token':csrfToken,'action':'resendVerificationEmail'}).done(function(data){jQuery('#btnResendVerificationEmail').prop('disabled',true);});});function parseMdeFooter(content,auto_save,saveText)
{saveText=saveText||saving;var pattern=/[a-zA-Z0-9_\u0392-\u03c9]+|[\u4E00-\u9FFF\u3400-\u4dbf\uf900-\ufaff\u3040-\u309f\uac00-\ud7af]+/g,m=[],word_count=0,line_count=0;if(content){m=content.match(pattern);line_count=content.split(/\\r\\n|\\r|\\n/).length;}
for(var i=0;i<m.length;i++){if(m[i].charCodeAt(0)>=0x4E00){word_count+=m[i].length;}else{word_count+=1;}}
return'<div class="small-font">lines: '+line_count+'&nbsp;&nbsp;&nbsp;words: '+word_count+''+(auto_save?'&nbsp;&nbsp;&nbsp;<span class="markdown-save">'+saveText+'</span>':'')+'</div>';}
function doCountdown()
{if(counter>=0){if(counter==0){jQuery("span.markdown-save").html(saved);}
counter--;setTimeout(doCountdown,1000);}}});function checkAll(className,masterControl){if(className[0]!='.'){className='.'+className;}
jQuery(className).removeAttr('checked');if(jQuery(masterControl).is(":checked")){jQuery(className).click();}}
function clickableSafeRedirect(clickEvent,target,newWindow){var eventSource=clickEvent.target.tagName.toLowerCase();var eventParent=clickEvent.target.parentNode.tagName.toLowerCase();var eventTable=clickEvent.target.parentNode.parentNode.parentNode;if(jQuery(eventTable).hasClass('collapsed')){return false;}
if(eventSource!='button'&&eventSource!='a'){if(eventParent!='button'&&eventParent!='a'){if(newWindow){window.open(target);}else{window.location.href=target;}}}}
function popupWindow(addr,popname,w,h,features){var winl=(screen.width-w)/2;var wint=(screen.height-h)/2;if(winl<0)winl=0;if(wint<0)wint=0;var settings='height='+h+',';settings+='width='+w+',';settings+='top='+wint+',';settings+='left='+winl+',';settings+=features;win=window.open(addr,popname,settings);win.window.focus();}
function addRenewalToCart(renewalID,selfThis){jQuery("#domainRow"+renewalID).attr('disabled','disabled');jQuery("#domainRow"+renewalID).find("select,button").attr("disabled","disabled");jQuery(selfThis).html('<span class="glyphicon glyphicon-shopping-cart"></span> Adding...');var renewalPeriod=jQuery("#renewalPeriod"+renewalID).val();jQuery.post("clientarea.php","addRenewalToCart=1&token="+csrfToken+"&renewID="+renewalID+"&period="+renewalPeriod,function(data){jQuery("#cartItemCount").html(((jQuery("#cartItemCount").html()*1)+1));jQuery(selfThis).html('<span class="glyphicon glyphicon-shopping-cart"></span> Added');jQuery("#btnCheckout").fadeIn();});}
function selectChangeNavigate(select){window.location.href=$(select).val();}
function extraTicketAttachment(){jQuery("#fileUploadsContainer").append('<input type="file" name="attachments[]" class="form-control" />');}
function dialogSubmit(){jQuery('div#twofaactivation form').attr('method','post');jQuery('div#twofaactivation form').attr('action','clientarea.php?action=security');jQuery('div#twofaactivation form').attr('onsubmit','');jQuery('div#twofaactivation form').submit();return true;}
function getStats(num){jQuery.post('serverstatus.php','getstats=1&num='+num,function(data){jQuery("#load"+num).html(data.load);jQuery("#uptime"+num).html(data.uptime);},'json');}
function checkPort(num,port){jQuery.post('serverstatus.php','ping=1&num='+num+'&port='+port,function(data){jQuery("#port"+port+"_"+num).html(data);});}
function getticketsuggestions(){currentcheckcontent=jQuery("#message").val();if(currentcheckcontent!=lastcheckcontent&&currentcheckcontent!=""){jQuery.post("submitticket.php",{action:"getkbarticles",text:currentcheckcontent},function(data){if(data){jQuery("#searchresults").html(data);jQuery("#searchresults").hide().removeClass('hidden').slideDown();}});lastcheckcontent=currentcheckcontent;}
setTimeout('getticketsuggestions();',3000);}
function refreshCustomFields(input){jQuery("#customFieldsContainer").load("submitticket.php",{action:"getcustomfields",deptid:$(input).val()});}
function autoSubmitFormByContainer(containerId){jQuery("#"+containerId).find("form:first").submit();}
function useDefaultWhois(regType){jQuery("."+regType.substr(0,regType.length-1)+"customwhois").attr("disabled",true);jQuery("."+regType.substr(0,regType.length-1)+"defaultwhois").attr("disabled",false);jQuery('#'+regType.substr(0,regType.length-1)+'1').attr("checked","checked");}
function useCustomWhois(regType){jQuery("."+regType.substr(0,regType.length-1)+"customwhois").attr("disabled",false);jQuery("."+regType.substr(0,regType.length-1)+"defaultwhois").attr("disabled",true);jQuery('#'+regType.substr(0,regType.length-1)+'2').attr("checked","checked");}
function editBillingAddress(){jQuery("#billingAddressSummary").hide();jQuery(".cc-billing-address").hide().removeClass('hidden').fadeIn();}
function showNewCardInputFields(){if(jQuery(".cc-details").hasClass("hidden")){jQuery(".cc-details").hide().removeClass("hidden");}
jQuery(".cc-details").slideDown();jQuery("#btnEditBillingAddress").removeAttr("disabled");}
function hideNewCardInputFields(){jQuery(".cc-billing-address").slideUp();jQuery(".cc-details").slideUp();jQuery("#btnEditBillingAddress").attr("disabled","disabled");if(jQuery("#billingAddressSummary").hasClass('hidden')){jQuery("#billingAddressSummary").hide().removeClass('hidden').slideDown();}else{jQuery("#billingAddressSummary").slideDown();}}
var lastTicketMsg;function getTicketSuggestions(){var userMsg=jQuery("#inputMessage").val();if(userMsg!=lastTicketMsg&&userMsg!=''){jQuery.post("submitticket.php",{action:"getkbarticles",text:userMsg},function(data){if(data){jQuery("#autoAnswerSuggestions").html(data);if(!jQuery("#autoAnswerSuggestions").is(":visible")){jQuery("#autoAnswerSuggestions").hide().removeClass('hidden').slideDown();}}});lastTicketMsg=userMsg;}
setTimeout('getTicketSuggestions()',3000);}
function deleteContact(confirmQuestion,contactId)
{if(confirm(confirmQuestion)){window.location='clientarea.php?action=contacts&delete=true&id='+contactId+'&token='+csrfToken;}}